# Generated by Django 3.1 on 2020-09-03 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='can_text',
            field=models.BooleanField(default=False, verbose_name='By signing up, you consent to receive periodic text messages from When We All Vote (56005). Message and data rates may apply. Text HELP for more information. Text STOP to stop receiving messages.'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='john', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1234567890, help_text='Use the same phone number that you used to register your Outvote account, if you have one', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits and entered in the format: '1234567890'.", regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default=12345, max_length=5, validators=[django.core.validators.RegexValidator(message="ZIP Code must be 5 digits and entered in the format: '12345'.", regex='^\\d{5}$')], verbose_name='ZIP Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='j@j.me', max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
