# Generated by Django 3.1 on 2020-09-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200901_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='reg',
            field=models.IntegerField(default=0),
        ),
    ]
