# Generated by Django 3.1 on 2020-09-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200903_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='reg_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'This URL is already taken'}, help_text='Choose a custom URL (Example: janedoe89) to make your page your own! Remember - once you choose a URL, you won’t be able to change it later. Make it fun: use your Instagram, Twitter, MySpace, or even AOL username!', max_length=30, null=True, unique=True, verbose_name='Your Custom URL'),
        ),
    ]
