# Generated by Django 3.1 on 2020-09-04 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200904_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='reg_complete',
            new_name='reg_started',
        ),
    ]
