# Generated by Django 3.1 on 2020-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200904_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='tracking',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
