# Generated by Django 3.1 on 2020-09-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200911_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='image',
            field=models.ImageField(blank=True, upload_to='referrer/'),
        ),
    ]
