# Generated by Django 3.1 on 2020-09-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='core.volunteer'),
        ),
    ]
