# Generated by Django 3.1 on 2020-09-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='actblue_donations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='actblue_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
