# Generated by Django 3.1 on 2020-09-02 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200901_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1234567890'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='prompt',
            field=models.TextField(max_length=2000, verbose_name='Voting Prompt'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'This URL is already taken'}, max_length=30, null=True, unique=True, verbose_name='Your Custom URL Suffix'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Page Title'),
        ),
    ]
