# Generated by Django 3.1 on 2020-09-02 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200902_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1234567890'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'This URL is already taken'}, help_text='Once you choose a URL, you may not change it later', max_length=30, null=True, unique=True, verbose_name='Your Custom URL Suffix'),
        ),
    ]
