# Generated by Django 3.1 on 2020-09-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200921_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='actblue_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
