# Generated by Django 3.1 on 2020-09-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200921_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
