# Generated by Django 3.1 on 2020-09-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200902_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='outvoteTexts',
            field=models.IntegerField(default=0),
        ),
    ]
