# Generated by Django 3.1 on 2020-09-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_volunteer_outvotetexts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='outvoteTexts',
            new_name='outvote_texts',
        ),
    ]
