# Generated by Django 3.1 on 2020-09-02 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200902_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='zip_code',
            field=models.CharField(default=12345, max_length=5, validators=[django.core.validators.RegexValidator(message="ZIP Code must be 5 digits and entered in the format: '12345'.", regex='^\\d{5}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(help_text='Use the same phone number that you used to register your Outvote account, if you have one', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits and entered in the format: '1234567890'.", regex='^\\d{10}$')]),
        ),
    ]
